service: authService
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    CLIENT_ID: ${ssm:/my-app/client-id}




functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  signUp:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /signUp
          method: post
  confirmSignup:
    handler: handlers/confirmSignup.confirmSignup
    events:
      - httpApi:
          path: /confirmSignup
          method: post
  signIn:
    handler: handlers/signIn.signIn
    events:
      - httpApi:
          path: /signIn
          method: post
  signOut:
    handler: handlers/signOut.signOut
    events:
      - httpApi:
          path: /signOut
          method: post
  

